baseURL = 'https://aimmetal-tech.github.io/'
locale = 'zh-cn'
title = "生活&技术&学习"
theme = "paper"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
  color = "linen"
  github = "aimmetal-tech"
  rss = true
  name = "AimMetal"
  bio = "Simple makes Complex"
  math = true