baseURL = 'https://liuliurq.com/'
locale = 'zh-cn'
title = "生活&技术&学习"
theme = "paper"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[params]
  color = "linen"
  github = "aimmetal-tech"
  rss = true
  name = "liuliurq - AimMetal"
  bio = "Simple makes Complex"
  math = true
  icp = "桂ICP备2026010684号-1"
